name: persistent_user_dir_access_android
description: "A package that leverages androids ACTION_OPEN_DOCUMENT_TREE and persists write permissions for a user chosen directory."
version: 0.0.2
repository: https://github.com/derdilla/persistent_user_dir_access_android
issue_tracker: https://github.com/derdilla/persistent_user_dir_access_android/issues
topics:
  - storage
  - picker
  - android
  - directory-picker
  - file-selection

environment:
  sdk: ^3.12.0
  flutter: '>=3.44.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.derdilla.persistent_user_dir_access_android
        pluginClass: PersistentUserDirAccessAndroidPlugin
